services:
  # Backend Service
  - type: web
    name: inventory-backend
    env: node
    rootDir: app/server
    buildCommand: npm install && node seed_users.js && node migrate_csv_to_pg.js
    startCommand: node index.js
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend Service
  - type: web
    name: inventory-frontend
    env: static
    rootDir: app/client
    buildCommand: rm -rf node_modules dist && npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://inventory-backend-up6a.onrender.com

databases:
  - name: inventory-db
    databaseName: inventario_db
    user: inventory_user
    plan: free # Optional: explicitly request free tier if available
